#ifndef COMPILER_ERRORS
#define COMPILER_ERRORS

#define NPP_UNIDENTIFIED_ARG 15
#define CMP_ERROR_EOF -15
#define CMP_ERROR_UNIDENTIFIED_TOKEN -125
#define CMP_ERROR_FILE_READ_FAIL 89
#define CMP_ERROR_CANT_OPEN -1
#define CMP_ERROR_UNEXPECTED_TOKEN 2

#define CMP_ERROR_TESTING 8

#define PARSE_ERROR_EOF 11283
#define PARSE_ERROR_INVALID_EXPRESSION 23
#define PARSE_ERROR_INVALID_ASSIGNMENT 21
#define PARSE_ERROR_NO_SEMICOLON 12
#define PARSE_ERROR_INVALID_VARIABLE_DECLERATION 76
#define PARSE_ERROR_INVALID_FUNCTION_CALL 9802
#define PARSE_ERROR_INVALID_KEYWORD_USE 192
#define PARSE_ERROR_NO_PARENTHESIS 981
#define PARSE_ERROR_EXPECTED_IDENTIFER 8912
#define PARSE_ERROR_NO_CURLY_BRACE 2654
#define PARSE_ERROR_NO_ARGUMENT_DECLERATION 85
#define PARSE_ERROR_NO_ARGUMENT_NAME 92
#define PARSE_ERROR_INVALID_PARAMETER 63
#endif