#ifndef COMPILER_ERRORS
#define COMPILER_ERRORS

int NPP_UNIDENTIFIED_ARG = 15;

int CMP_ERROR_EOF = -15;
int CMP_ERROR_UNIDENTIFIED_TOKEN = -125;
int CMP_ERROR_FILE_READ_FAIL = 89;
int CMP_ERROR_CANT_OPEN = -1;
#endif